### ISSUE TITLE
Missing package.json or package-lock.json

### ISSUE THREAD

**Issue by dev-platong** [Knifer110/Shobo_chat#1]
依存関係がどうなっているかがわからないので、
package.jsonまたはpackage-lock.jsonのどちらかが必要です。
gitignoreを変更するか、package-lock.jsonを生成するかしてください。

**Comment by Knifer110** [comment]
追加できたはずです。ただGitに不慣れなので変なことをやってしまった可能性が高いです。

**Comment by Knifer110** [comment]
これもとりあえずできてそうなので閉じます。
