### ISSUE TITLE
Conflictを解消する

### ISSUE THREAD

**Issue by dev-platong** [Knifer110/Shobo_chat#2]
https://github.com/Knifer110/Shobo_chat/commit/d46472ccfa4138bba63c52ae09cb1ecbcf4aee43

これを見る限りわかってなさそうだったので、コンフリクトの解消について勉強した上で打ち消しコミットするとよさそう。

**Comment by Knifer110** [comment]
了解です。subscribeできたかの確認も含めてコメントしておきます。

**Comment by Knifer110** [comment]
おそらく解消できたので閉じます。
